version: "2"
services:
  nginx:
    extends:
      file: base.yml
      service: nginx
    links:
      - app

  postgres:
    extends:
      file: base.yml
      service: postgres

  redis:
    extends:
      file: base.yml
      service: redis

  app:
    restart: always
    extends:
      file: base.yml
      service: app
    environment:
      - DJANGO_SETTINGS_MODULE=uploader.settings.dev
    build:
      args:
        - DJANGO_ENV=dev
    links:
      - redis
      - postgres
    env_file: .env

  worker:
    extends:
      file: base.yml
      service: worker
    environment:
      - DJANGO_SETTINGS_MODULE=uploader.settings.dev
    build:
      args:
        - DJANGO_ENV=dev
    links:
      - redis
      - postgres

  beat:
    extends:
      file: base.yml
      service: beat
    environment:
      - DJANGO_SETTINGS_MODULE=uploader.settings.dev
    build:
      args:
        - DJANGO_ENV=dev
    links:
      - redis
      - postgres
